services:
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DB_NAME=gamify360DB
      - DB_USER=gamify360db_owner
      - DB_PASS=B6uwaNdG9HEP
      - DB_PORT=5432
      - DB_SERVICE=db
      - DJANGO_ALLOWED_HOSTS='localhost,api.erfanfaravani.ir'

    container_name: backend
    expose:
      - "8000"
    networks:
      - network

  frontend:
    build: ./web-app
    container_name: frontend
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    networks:
      - network


  db:
    image: postgres
    environment:
      POSTGRES_USER: gamify360db_owner
      POSTGRES_PASSWORD: B6uwaNdG9HEP
      POSTGRES_DB: gamify360DB
    networks:
      - network
    volumes:
      - psql-data:/var/lib/postgres/data
    restart: always
    ports:
      - 5432:5432

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d   # ✅ this mounts your config folder
    networks:
      - network
    depends_on:
      # - db
      # - backend
      - frontend

networks:
  network:

volumes:
  psql-data:
    driver: local
