# Generated by Django 5.1 on 2025-04-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('score', models.IntegerField(default=0)),
                ('answers', models.IntegerField(default=0)),
                ('has_spun', models.BooleanField(default=False)),
                ('prize', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
